services:
  server:
    image: shabheeh/treatme-server:latest
    container_name: mern-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
      - NODE_ENV=production
      # Puppeteer configuration
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    depends_on:
      - redis
    volumes:
      - puppeteer_cache:/app/.cache
    networks:
      - treatme-network
    shm_size: 2gb  # Increased shared memory for Chrome
    deploy:
      resources:
        limits:
          memory: 3G  # Increased memory limit for Chrome
        reservations:
          memory: 1.5G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined  # Required for Chrome to work in Docker

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - treatme-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  puppeteer_cache:
    driver: local

networks:
  treatme-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
